import sharp from "sharp";
import fs from "node:fs/promises";
const source = process.argv[2] || "resources/icon-source.png";
await fs.mkdir("resources", { recursive: true });
const png = await sharp(source).resize(256, 256, { fit: "cover" }).png().toBuffer();
await fs.writeFile("resources/icon.png", png);
const header = Buffer.alloc(22);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(1, 4);
header.writeUInt16LE(1, 10);
header.writeUInt16LE(32, 12);
header.writeUInt32LE(png.length, 14);
header.writeUInt32LE(22, 18);
await fs.writeFile("resources/icon.ico", Buffer.concat([header, png]));
